### ISSUE TITLE
"The file "/private/var/tmp/phpAocs14" does not exist" on upload. 

### ISSUE THREAD

**Issue by danmatthews** [spatie/laravel-medialibrary#1062]
Getting this when uploading an image file - been using this (fantastic) package on my local environment for another project and it works great, but with this one i'm uploading images.

I've temporarily fixed this by adding `preservingOriginal()` as the middle method so it doesn't try and cleanup the tmp file.

Does this look like an issue with my system or with the package?

- PHP 7.1.13
- Laravel Valet v2.0.12

Composer show:

```
spatie/image                          1.5.1   Manipulate images with an expressive API
spatie/image-optimizer                1.0.14  Easily optimize images using PHP
spatie/laravel-medialibrary           7.1.7   Associate files with Eloquent models
spatie/laravel-permission             2.12.1  Permission handling for Laravel 5.4 and up
spatie/pdf-to-image                   1.2.2   Convert a pdf to an image
spatie/temporary-directory            1.1.4   Easily create, use and destroy temporary directories
```

Full trace:

```
[2018-04-25 10:27:14] local.ERROR: The file "/private/var/tmp/phpiTAchk" does not exist {"userId":1,"email":"dan@danmatthews.me","exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"/private/var/tmp/phpiTAchk\" does not exist at /Users/danmatthews/Sites/vle-redux/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php:121)
[stacktrace]
#0 /Users/danmatthews/Sites/vle-redux/vendor/symfony/http-foundation/File/File.php(79): Symfony\\Component\\HttpFoundation\\File\\MimeType\\MimeTypeGuesser->guess('/private/var/tm...')
#1 /Users/danmatthews/Sites/vle-redux/vendor/symfony/http-foundation/File/File.php(58): Symfony\\Component\\HttpFoundation\\File\\File->getMimeType()
#2 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(990): Symfony\\Component\\HttpFoundation\\File\\File->guessExtension()
#3 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(365): Illuminate\\Validation\\Validator->validateMimes('logo', Object(Illuminate\\Http\\UploadedFile), Array, Object(Illuminate\\Validation\\Validator))
#4 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(268): Illuminate\\Validation\\Validator->validateAttribute('logo', 'Mimes')
#5 /Users/danmatthews/Sites/vle-redux/app/Http/Controllers/OrganisationController.php(91): Illuminate\\Validation\\Validator->passes()
#6 [internal function]: App\\Http\\Controllers\\OrganisationController->update(Object(Illuminate\\Http\\Request), Object(App\\Organisation))
#7 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#8 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#9 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\OrganisationController), 'update')
#10 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#11 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Route->run()
#12 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/danmatthews/Sites/vle-redux/vendor/spatie/laravel-permission/src/Middlewares/RoleMiddleware.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Spatie\\Permission\\Middlewares\\RoleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'super-admin')
#15 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#39 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#40 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#41 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#42 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#43 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/danmatthews/Sites/vle-redux/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /Users/danmatthews/Sites/vle-redux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#62 /Users/danmatthews/Sites/vle-redux/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#63 /Users/danmatthews/.composer/vendor/laravel/valet/server.php(147): require('/Users/danmatth...')
#64 {main}
"}
```

**Comment by freekmurze** [comment]
I'm thinking it has something to do with your system, because the tests of this package run fine, both locally as on Travis.

**Comment by tantana5** [comment]
I have same issue true, it happens when your form validate fails and redirects back

**Comment by krns** [comment]
We also have the same problem. We are developing inside a docker container. 

Do you have some ideas what system settings could cause this problem @freekmurze?

**Comment by simonbowen** [comment]
I'm also getting this issue on a standard ubuntu 18.04 server. Any one got any pointers?

**Comment by emprove** [comment]
I'm faced with this issue inside docker. On locally all fine, but on prod no. I'm using the same php configs both for local/prod. It would be good to shed light on the problem.

**Comment by glenprimitivesense** [comment]
Did anyone figure anything with this issue?

**Comment by emprove** [comment]
preservingOriginal() fix the problem.

**Comment by glenprimitivesense** [comment]
Hey @emprove I'm not so sure I understand can you give me a little more direction?

**Comment by Canser** [comment]
Hi.

Updated to latest package, it's happening right now. 

On my mac without a docker container; I am using Valet but still got this error.

It was working before, maybe I should check the version differences before and after.

On my mac; I get:

> "message": "File `/private/var/tmp/phpZqjpsI` does not exist",
> "exception": "Spatie\\MediaLibrary\\Exceptions\\FileCannotBeAdded\\FileDoesNotExist",
> "file": "/Users/canser/PhpstormProjects/coobly/vendor/spatie/laravel-medialibrary/src/Exceptions/FileCannotBeAdded/FileDoesNotExist.php",
>  "line": 11,

On the server (ubuntu) It's similar but the temp dir is different.

I will write here if I find something.

**Comment by arnakoguzhan** [comment]
> Hi.
> 
> Updated to latest package, it's happening right now.
> 
> On my mac without a docker container; I am using Valet but still got this error.
> 
> It was working before, maybe I should check the version differences before and after.
> 
> On my mac; I get:
> 
> > "message": "File `/private/var/tmp/phpZqjpsI` does not exist",
> > "exception": "Spatie\MediaLibrary\Exceptions\FileCannotBeAdded\FileDoesNotExist",
> > "file": "/Users/canser/PhpstormProjects/coobly/vendor/spatie/laravel-medialibrary/src/Exceptions/FileCannotBeAdded/FileDoesNotExist.php",
> > "line": 11,
> 
> On the server (ubuntu) It's similar but the temp dir is different.
> 
> I will write here if I find something.

Same as @Canser. Both my mac and on the server Ubuntu have the same issue while I trying to add multiple images from request using addAllMediaFromRequest(). 

Also, an interesting thing, when I was trying to edit existing model (or newly created model) the function above works. I could not figure it out that it happened when I try to store a new model.

**Comment by ilBronza** [comment]
it happens when I try to run 

$modelOne->addMediaFromRequest('file')->toMediaCollection('something');
$modelTwo->addMediaFromRequest('file')->toMediaCollection('something');

if I run just one time addMediaFromRequest('file') it works 
(like this)

$modelOne->addMediaFromRequest('file')->toMediaCollection('something');
//$modelTwo->addMediaFromRequest('file')->toMediaCollection('something');

it seems that (correctly) remove the tmp file after the first addMediaFromRequest calling, maybe its the same when using addAllMediaFromRequest

**Comment by pedrorocha-net** [comment]
I can confir

> it happens when I try to run
> 
> ```
> $modelOne->addMediaFromRequest('file')->toMediaCollection('something');
> $modelTwo->addMediaFromRequest('file')->toMediaCollection('something');
> ```
> 
> if I run just one time addMediaFromRequest('file') it works
> (like this)
> 
> ```
> $modelOne->addMediaFromRequest('file')->toMediaCollection('something');
> //$modelTwo->addMediaFromRequest('file')->toMediaCollection('something');
> ```
> 
> it seems that (correctly) remove the tmp file after the first addMediaFromRequest calling, maybe its the same when using addAllMediaFromRequest

I can confirm that I had the same issue and after seeing this comment here, I double-checked my code and it was calling the "addMediaFromRequest('file')" twice, by mistake. By removing the second call, it solved the issue.

No error on the package, but on developers logic/code.
