### ISSUE TITLE
Conversion fails on queue but works without queue.

### ISSUE THREAD

**Issue by shirshak55** [spatie/laravel-medialibrary#1296]
I have configured media like this:

```
        'media' => [
            'driver'     => 'local',
            'root'       => "/home/shirshak55/media",
            'url'        => env('APP_URL').'/media',
            'visibility' => 'public',
        ],
```

I have setup `custom root` which can be seen.  Laravel is in another folder. I have used disk as `media` on medialibrary configuration.

I have defined conversion like this.
```
    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(200)
            ->height(250)
            ->sharpen(10)
            ->optimize()
            ->nonQueued();
    }
```

If i put `nonQueued` it works fine. But When i queue it shows this weird error which is pain to debug. In Horizon at failed job it shows

```
Spatie\MediaLibrary\Jobs\PerformConversions
ID
1
Queue
default
Tags
Spatie\MediaLibrary\Models\Media:563
Failed At
18-11-02 19:24:37
Error
League\Flysystem\FileNotFoundException: File not found at path: 563/Screen-Shot-2018-10-28-at-11.25.22-PM.png in /home/boldscholar/boldscholar/vendor/league/flysystem/src/Filesystem.php:388
Stack trace:
#0 /home/boldscholar/boldscholar/vendor/league/flysystem/src/Filesystem.php(194): League\Flysystem\Filesystem->assertPresent('563/Screen-Shot...')
#1 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(405): League\Flysystem\Filesystem->readStream('563/Screen-Shot...')
#2 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(80): Illuminate\Filesystem\FilesystemAdapter->readStream('563//Screen-Sho...')
#3 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(87): Spatie\MediaLibrary\Filesystem\Filesystem->getStream(Object(Spatie\MediaLibrary\Models\Media))
#4 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(76): Spatie\MediaLibrary\Filesystem\Filesystem->copyFromMediaLibrary(Object(Spatie\MediaLibrary\Models\Media), '/home/boldschol...')
#5 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php(32): Spatie\MediaLibrary\FileManipulator->performConversions(Object(Spatie\MediaLibrary\Conversion\ConversionCollection), Object(Spatie\MediaLibrary\Models\Media))
#6 [internal function]: Spatie\MediaLibrary\Jobs\PerformConversions->handle()
#7 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#8 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#10 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#11 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#12 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#13 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#14 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Spatie\MediaLibrary\Jobs\PerformConversions), false)
#16 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#17 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#18 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#19 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#20 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#21 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#22 /home/boldscholar/boldscholar/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#23 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#24 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#29 /home/boldscholar/boldscholar/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /home/boldscholar/boldscholar/vendor/symfony/console/Application.php(894): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/boldscholar/boldscholar/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/boldscholar/boldscholar/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/boldscholar/boldscholar/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}
Next Illuminate\Contracts\Filesystem\FileNotFoundException: File not found at path: 563/Screen-Shot-2018-10-28-at-11.25.22-PM.png in /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:409
Stack trace:
#0 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(80): Illuminate\Filesystem\FilesystemAdapter->readStream('563//Screen-Sho...')
#1 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(87): Spatie\MediaLibrary\Filesystem\Filesystem->getStream(Object(Spatie\MediaLibrary\Models\Media))
#2 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(76): Spatie\MediaLibrary\Filesystem\Filesystem->copyFromMediaLibrary(Object(Spatie\MediaLibrary\Models\Media), '/home/boldschol...')
#3 /home/boldscholar/boldscholar/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php(32): Spatie\MediaLibrary\FileManipulator->performConversions(Object(Spatie\MediaLibrary\Conversion\ConversionCollection), Object(Spatie\MediaLibrary\Models\Media))
#4 [internal function]: Spatie\MediaLibrary\Jobs\PerformConversions->handle()
#5 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#10 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#11 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#12 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Spatie\MediaLibrary\Jobs\PerformConversions), false)
#14 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#15 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#16 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#17 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#18 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#19 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#20 /home/boldscholar/boldscholar/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#21 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#22 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#23 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#27 /home/boldscholar/boldscholar/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 /home/boldscholar/boldscholar/vendor/symfony/console/Application.php(894): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /home/boldscholar/boldscholar/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /home/boldscholar/boldscholar/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/boldscholar/boldscholar/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/boldscholar/boldscholar/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}
```

And file do really exist but league filesystem is unable to identify. It seems like on `queue` `medialibrary` is not using specified disk properly

**Comment by nicolasbeauvais** [comment]
Hello @shirshak55, could you share the code used to add the media?

**Comment by shirshak55** [comment]
@nicolasbeauvais hmm it is done by nova media library.

And how is this related to add media. It is case where without queue it works but without it it don't works

https://github.com/jameslkingsley/nova-media-library

**Comment by shirshak55** [comment]
@nicolasbeauvais hmm it is not looking for correct file if you check. It is using relative filesystem. According to that issue job get run before model is saved. But it seem it is getting model correctly

**Comment by chancezeus** [comment]
I'm not using Nova but I am having the same issue and in my case it is caused because the model is created inside a database transaction. This causes the model to only exist on the same connection it is created (hence it does work with sync/disabled queue) but be invisible until the transaction is committed for any other connection (hence it does not work with async queue). I would suggest that the package is updated so the scheduled job is run with a configurable (short) delay (i.e. default 0, but configurable to for example 1s (which should be enough for the transaction to actually be completed).

**Comment by freekmurze** [comment]
Closing due to inactivity.

**Comment by shirshak55** [comment]
hmm but is it fixed?

**Comment by elfeffe** [comment]
> hmm but is it fixed?

No, I'm using
 $this
                ->addMediaConversion('big')
                ->optimize()
                ->nonQueued()
            ;

With the last version, and it works only if non queued.

**Comment by MooseSaeed** [comment]
> > hmm but is it fixed?
> 
> No, I'm using $this ->addMediaConversion('big') ->optimize() ->nonQueued() ;
> 
> With the last version, and it works only if non queued.

 Same

**Comment by mudassirali007** [comment]
What if I wanted to add the media conversion in custom queue, like this
// in your model
```
public function registerMediaConversions(Media $media = null): void
{
    $this->addMediaConversion('thumb')
            ->width(368)
            ->height(232)
            ->queued('custom-queue');
}
```
is there a solution for this?
