### ISSUE TITLE
Problem with queued conversions in Spatie\MediaLibrary\Jobs\PerformConversions

### ISSUE THREAD

**Issue by bstrahija** [spatie/laravel-medialibrary#1481]
So we have setup that takes uploaded images and adds them to the media library. Once in a while the queued jobs simply stop working and the error in the log is this one:

    Symfony\Component\Process\Exception\RuntimeException: The provided cwd does not exist. in /var/www/vendor/symfony/process/Process.php:334

The current setup runs through a docker container, but the same thing happens on a regular server. And once the queue worker is restarted everything starts working again.

The full stack trace:

```
#0 /var/www/vendor/symfony/process/Process.php(233): Symfony\Component\Process\Process->start(NULL, Array)
#1 /var/www/vendor/spatie/image-optimizer/src/OptimizerChain.php(101): Symfony\Component\Process\Process->run()
#2 /var/www/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Jpegoptim), Object(Spatie\ImageOptimizer\Image))
#3 /var/www/vendor/spatie/image/src/Image.php(158): Spatie\ImageOptimizer\OptimizerChain->optimize('/var/www/storag...')
#4 /var/www/vendor/spatie/image/src/Image.php(137): Spatie\Image\Image->performOptimization('/var/www/storag...', Array)
#5 /var/www/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(142): Spatie\Image\Image->save()
#6 /var/www/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(96): Spatie\MediaLibrary\FileManipulator->performManipulations(Object(SL\Media\Media), Object(Spatie\MediaLibrary\Conversion\Conversion), '/var/www/storag...')
#7 /var/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php(397): Spatie\MediaLibrary\FileManipulator->Spatie\MediaLibrary\{closure}(Object(Spatie\MediaLibrary\Conversion\Conversion), 0)
#8 /var/www/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(117): Illuminate\Support\Collection->each(Object(Closure))
#9 /var/www/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php(32): Spatie\MediaLibrary\FileManipulator->performConversions(Object(Spatie\MediaLibrary\Conversion\ConversionCollection), Object(SL\Media\Media))
#10 [internal function]: Spatie\MediaLibrary\Jobs\PerformConversions->handle()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#17 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Spatie\MediaLibrary\Jobs\PerformConversions), false)
#20 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(326): Illuminate\Queue\Jobs\Job->fire()
#22 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(276): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'op3_hub', Object(Illuminate\Queue\WorkerOptions))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'op3_hub')
#26 /var/www/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#27 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#28 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#29 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#32 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\Container\Container->call(Array)
#33 /var/www/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#35 /var/www/vendor/symfony/console/Application.php(908): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 {main}
```

And the data that is passed to the queue:

```
{
  "conversions": {
    "media": null,
    "items": [
      {
        "name": "small",
        "extractVideoFrameAtSecond": 0,
        "manipulations": {
          "manipulationSequence": {
            "groups": [
              {
                "optimize": "{\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Jpegoptim\":[\"--strip-all\",\"--all-progressive\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Pngquant\":[\"--force\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Optipng\":[\"-i0\",\"-o2\",\"-quiet\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Svgo\":[\"--disable=cleanupIDs\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Gifsicle\":[\"-b\",\"-O3\"]}",
                "format": "jpg",
                "width": "400"
              }
            ]
          }
        },
        "performOnCollections": [],
        "performOnQueue": true,
        "keepOriginalImageFormat": false,
        "generateResponsiveImages": false
      },
      {
        "name": "medium",
        "extractVideoFrameAtSecond": 0,
        "manipulations": {
          "manipulationSequence": {
            "groups": [
              {
                "optimize": "{\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Jpegoptim\":[\"--strip-all\",\"--all-progressive\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Pngquant\":[\"--force\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Optipng\":[\"-i0\",\"-o2\",\"-quiet\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Svgo\":[\"--disable=cleanupIDs\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Gifsicle\":[\"-b\",\"-O3\"]}",
                "format": "jpg",
                "width": "800"
              }
            ]
          }
        },
        "performOnCollections": [],
        "performOnQueue": true,
        "keepOriginalImageFormat": false,
        "generateResponsiveImages": false
      },
      {
        "name": "large",
        "extractVideoFrameAtSecond": 0,
        "manipulations": {
          "manipulationSequence": {
            "groups": [
              {
                "optimize": "{\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Jpegoptim\":[\"--strip-all\",\"--all-progressive\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Pngquant\":[\"--force\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Optipng\":[\"-i0\",\"-o2\",\"-quiet\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Svgo\":[\"--disable=cleanupIDs\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Gifsicle\":[\"-b\",\"-O3\"]}",
                "format": "jpg",
                "width": "1600"
              }
            ]
          }
        },
        "performOnCollections": [],
        "performOnQueue": true,
        "keepOriginalImageFormat": false,
        "generateResponsiveImages": false
      },
      {
        "name": "xl",
        "extractVideoFrameAtSecond": 0,
        "manipulations": {
          "manipulationSequence": {
            "groups": [
              {
                "optimize": "{\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Jpegoptim\":[\"--strip-all\",\"--all-progressive\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Pngquant\":[\"--force\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Optipng\":[\"-i0\",\"-o2\",\"-quiet\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Svgo\":[\"--disable=cleanupIDs\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Gifsicle\":[\"-b\",\"-O3\"]}",
                "format": "jpg",
                "width": "5000"
              }
            ]
          }
        },
        "performOnCollections": [],
        "performOnQueue": true,
        "keepOriginalImageFormat": false,
        "generateResponsiveImages": false
      },
      {
        "name": "thumb",
        "extractVideoFrameAtSecond": 0,
        "manipulations": {
          "manipulationSequence": {
            "groups": [
              {
                "optimize": "{\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Jpegoptim\":[\"--strip-all\",\"--all-progressive\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Pngquant\":[\"--force\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Optipng\":[\"-i0\",\"-o2\",\"-quiet\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Svgo\":[\"--disable=cleanupIDs\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Gifsicle\":[\"-b\",\"-O3\"]}",
                "format": "jpg",
                "width": "320",
                "height": "320",
                "fit": "crop"
              }
            ]
          }
        },
        "performOnCollections": [],
        "performOnQueue": true,
        "keepOriginalImageFormat": false,
        "generateResponsiveImages": false
      }
    ]
  },
  "media": {
    "class": "SL\\Media\\Media",
    "id": 2968,
    "relations": [],
    "connection": "mysql_rw"
  },
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}
```

Anyone else experiencing similar issues?

**Comment by brendt** [comment]
I believe this has to do with file permissions. Please verify whether the user running horizon has all required permissions to write to the correct folders. 

I'll be closing this issue, as it doesn't seem to be anything we need to fix in this package, but feel free to keep the conversation going if you need any more input.

**Comment by bstrahija** [comment]
Ok, so we're still having this issue. We have 3 workers setup, and every worker has 3 processes with simple balancing. Since the conversions work on like every 5th/6th try, I'm guessing there an issue with 1 or 2 of those 3 workers.

So, is there a way to tell which worker is responsible for the failed job?
Our workers look something like this:

    some-dummy-app-q-worker-1-Z2Mu
    some-dummy-app-q-worker-2-7sYF
    some-dummy-app-q-worker-3-4GgA

Would be nice if I could somehow pinpoint the worker that handled the job when it fails, and when it works.

**Comment by IVNtech** [comment]
after DAYS trying to make it finally your server must have this installed on Linux Ubuntu nginx something called GD

sudo apt-get install php7.4-gd

test workig the GD with = php -i | grep -i gd

then restart the nginx

Something Called GD is in charge of handle the IMage content on the server

**Comment by MooseSaeed** [comment]
I'm facing the same issue
