### ISSUE TITLE
Return value of Spatie\MediaLibrary\PathGenerator\BasePathGenerator::getBasePath() must be of the type string, null returned

### ISSUE THREAD

**Issue by sudipt0** [spatie/laravel-medialibrary#1616]
**Getting an error in Laravel 6.2**

```
Symfony\Component\Debug\Exception\FatalThrowableError
Return value of Spatie\MediaLibrary\PathGenerator\BasePathGenerator::getBasePath() must be of the type string, null returned
```

`vendor/spatie/laravel-medialibrary/src/PathGenerator/BasePathGenerator.php:39`

**Comment by freekmurze** [comment]
The tests prove that the latest version of this package is working perfectly. Could you try installing the latest version of the pacakge in a vanilla laravel app and check if you are having problems there?

**Comment by danteYuX** [comment]
**I have the same error in Lumen 6.2.0**
Return value of Spatie\MediaLibrary\PathGenerator\BasePathGenerator::getBasePath() must be of the type string, null returned in .... /vendor/spatie/laravel-medialibrary/src/PathGenerator/BasePathGenerator.php:39

**Comment by myckhel** [comment]
I got same error when i tried to use custom model 
e.g `New Model`

checking this issue made me try the normal model and it worked https://github.com/spatie/laravel-medialibrary/issues/1036#issue-313783509

I dont know if its the same in your case.

**Comment by Bubalubs** [comment]
I had this error and it occurred because I didn't save the model first `$model->save()` before creating media to attach and calling `$media->getUrl()`

So check to make sure you save the model first and it exists in the database if you are calling that method.

**Comment by aliraza93** [comment]
I'm having the same error in **Laravel 7.0** while uploading image
The data gets uploaded in the database but image isn't saved and I get this error

Symfony\Component\Debug\Exception\FatalThrowableError
Return value of Spatie\MediaLibrary\PathGenerator\BasePathGenerator::getBasePath() must be of the type string, null returned

**Comment by josegus** [comment]
Same here, it happends when using a CustomMedia model and you save the parent model.

**Comment by fahad-larasoft** [comment]
@freekmurze I am using Medialibrary V6 in Laravel 5.5 and getting this error while downloading file. See screenshots below:

<img width="834" alt="Screenshot 2020-05-12 at 2 56 17 PM" src="https://user-images.githubusercontent.com/7126820/81670396-f831b580-9460-11ea-9207-fc5d0dd4dc16.png">

<img width="951" alt="Screenshot 2020-05-12 at 2 56 31 PM" src="https://user-images.githubusercontent.com/7126820/81670400-f8ca4c00-9460-11ea-9371-c1bb6a3b106b.png">

<img width="1440" alt="Screenshot 2020-05-12 at 2 56 10 PM" src="https://user-images.githubusercontent.com/7126820/81670390-f536c500-9460-11ea-8a13-c804824b3be7.png">

<img width="1429" alt="Screenshot 2020-05-12 at 2 55 01 PM" src="https://user-images.githubusercontent.com/7126820/81670372-ef40e400-9460-11ea-8638-b25f683cf020.png">

I can not upgrade Medialibrary because Laravel 5.5 is compatible with only Medialibrary V6.

Could you guys please resolve this issue in Medialibrary V6 ?

**Comment by ethanclevenger91** [comment]
I seem to be having this issue when casting the result of `toMediaCollection()` to a string. For example, in a controller, if I do:

```php
return $model->addMedia($file)
   ->toMediaCollectionOnCloudDisk($media_collection);
```

That error crops up.

**Comment by freekmurze** [comment]
Improvements on this were made in the latest version of the medialib. If possible, upgrade to the latest version.

**Comment by shirshak55** [comment]
actually i got this error so this issue has not been fixed.

**Comment by shirshak55** [comment]
getKey() seems to fails but the code seems ok

```
Spatie\MediaLibrary\MediaCollections\Models\Media {#1593
  #table: "media"
  #guarded: []
  #casts: array:3 [
    "manipulations" => "array"
    "custom_properties" => "array"
    "responsive_images" => "array"
  ]
  #connection: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: false
  +wasRecentlyCreated: false
  #attributes: array:10 [
    "name" => "newPhoto"
    "file_name" => "newPhoto.jpg"
    "disk" => "media"
    "conversions_disk" => "media"
    "collection_name" => "51620baf-7e05-4e72-b9a3-176a2cc419d0"
    "mime_type" => "image/jpeg"
    "size" => 29425
    "custom_properties" => "[]"
    "responsive_images" => "[]"
    "manipulations" => "[]"
  ]
  #original: []
  #changes: []
  #classCastCache: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #hidden: []
  #visible: []
  #fillable: []
}
```

Here is the error resp
```
{
    "message": "Return value of Spatie\\MediaLibrary\\Support\\PathGenerator\\DefaultPathGenerator::getBasePath() must be of the type string, null returned",
    "exception": "TypeError",
    "file": "/Users/quantum/Desktop/code/dumb_app/vendor/spatie/laravel-medialibrary/src/Support/PathGenerator/DefaultPathGenerator.php",
    "line": 38,
    "trace": [
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/spatie/laravel-medialibrary/src/Support/PathGenerator/DefaultPathGenerator.php",
            "line": 14,
            "function": "getBasePath",
            "class": "Spatie\\MediaLibrary\\Support\\PathGenerator\\DefaultPathGenerator",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/spatie/laravel-medialibrary/src/Support/UrlGenerator/BaseUrlGenerator.php",
            "line": 51,
            "function": "getPath",
            "class": "Spatie\\MediaLibrary\\Support\\PathGenerator\\DefaultPathGenerator",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/spatie/laravel-medialibrary/src/Support/UrlGenerator/DefaultUrlGenerator.php",
            "line": 12,
            "function": "getPathRelativeToRoot",
            "class": "Spatie\\MediaLibrary\\Support\\UrlGenerator\\BaseUrlGenerator",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php",
            "line": 64,
            "function": "getUrl",
            "class": "Spatie\\MediaLibrary\\Support\\UrlGenerator\\DefaultUrlGenerator",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/app/Nova/Patches/PTrix.php",
            "line": 70,
            "function": "getUrl",
            "class": "Spatie\\MediaLibrary\\MediaCollections\\Models\\Media",
            "type": "->"
        },
        {
            "function": "App\\Nova\\Patches\\{closure}",
            "class": "App\\Nova\\Patches\\PTrix",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/nova/src/Http/Controllers/TrixAttachmentController.php",
            "line": 25,
            "function": "call_user_func"
        },
        {
            "function": "store",
            "class": "Laravel\\Nova\\Http\\Controllers\\TrixAttachmentController",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/nova/src/Http/Middleware/Authorize.php",
            "line": 18,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authorize",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/nova/src/Http/Middleware/BootTools.php",
            "line": 20,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\BootTools",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/nova/src/Http/Middleware/DispatchServingNovaEvent.php",
            "line": 20,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",
            "line": 44,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/nova/src/Http/Middleware/Authenticate.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 76,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 116,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 62,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/kabbouchi/nova-impersonate/src/Http/Middleware/Impersonate.php",
            "line": 23,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "KABBOUCHI\\NovaImpersonate\\Http\\Middleware\\Impersonate",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/nova/src/Http/Middleware/ServeNova.php",
            "line": 26,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\ServeNova",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/fruitcake/laravel-cors/src/HandleCors.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/quantum/Desktop/code/dumb_app/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/quantum/.composer/vendor/laravel/valet/server.php",
            "line": 191,
            "function": "require"
        }
    ]
}
```

**Comment by typoworx-de** [comment]
> Is there still error. I got similar issue where getBasePath returns null .

Can confirm this... all versions above 9.0.0 seem to habe the issue. I'm running PHP 8.0 so any version below isn't tested. But before Migration to recent laravel the package worked fine with ```spatie/laravel-medialibrary:^7.0.0``` and PHP 7.4.

There's something wrong with Media::getKey() method?!

```
    public function getKey()
    {
        dd($this->getKeyName()) --> 'id'
        return $this->getAttribute($this->getKeyName());
    }
```

But the model doesn't seem to have id included in $this->getAttributes()!

**Comment by typoworx-de** [comment]
Ok... figured out I obvisouly had to persist the video before using addmedia. This fixed the id-problem mentioned above, but the next issue is right ahead.

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'conversions_disk' in 'field list'

**Comment by minkbear** [comment]
@typoworx-de This error happen to me too.

spatie/laravel-medialibrary : 9.6.4

```
[2021-06-26 22:07:34] prd.ERROR: Return value of Spatie\MediaLibrary\Support\PathGenerator\DefaultPathGenerator::getBasePath() must be of the type string, null returned {"exception":"[object] (TypeError(code: 0): Return value of Spatie\\MediaLibrary\\Support\\PathGenerator\\DefaultPathGenerator::getBasePath() must be of the type string, null returned at /var/www/test/vendor/spatie/laravel-medialibrary/src/Support/PathGenerator/DefaultPathGenerator.php:38)
[stacktrace]
#0 /var/www/test/vendor/spatie/laravel-medialibrary/src/Support/PathGenerator/DefaultPathGenerator.php(14): Spatie\\MediaLibrary\\Support\\PathGenerator\\DefaultPathGenerator->getBasePath(Object(App\\Models\\MediaJobs))
#1 /var/www/test/vendor/spatie/laravel-medialibrary/src/MediaCollections/Filesystem.php(300): Spatie\\MediaLibrary\\Support\\PathGenerator\\DefaultPathGenerator->getPath(Object(App\\Models\\MediaJobs))
#2 /var/www/test/vendor/spatie/laravel-medialibrary/src/MediaCollections/Filesystem.php(121): Spatie\\MediaLibrary\\MediaCollections\\Filesystem->getMediaDirectory(Object(App\\Models\\MediaJobs), NULL)
#3 /var/www/test/vendor/spatie/laravel-medialibrary/src/MediaCollections/Filesystem.php(30): Spatie\\MediaLibrary\\MediaCollections\\Filesystem->copyToMediaLibrary('/tmp/phpB9YjIU', Object(App\\Models\\MediaJobs), NULL, '1102001912398_i...')
#4 /var/www/test/vendor/spatie/laravel-medialibrary/src/MediaCollections/FileAdder.php(427): Spatie\\MediaLibrary\\MediaCollections\\Filesystem->add('/tmp/phpB9YjIU', Object(App\\Models\\MediaJobs), '1102001912398_i...')
#5 /var/www/test/vendor/spatie/laravel-medialibrary/src/MediaCollections/FileAdder.php(413): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->processMediaItem(Object(App\\Models\\Jobs), Object(App\\Models\\MediaJobs), Object(Spatie\\MediaLibrary\\MediaCollections\\FileAdder))
#6 /var/www/test/vendor/spatie/laravel-medialibrary/src/MediaCollections/FileAdder.php(334): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->attachMedia(Object(App\\Models\\MediaJobs))
#7 /var/www/test/app/Http/Controllers/API/UploadsAPIController.php(51): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->toMediaCollection('test')
```

I custom media model below:

```
<?php

namespace App\Models;

use Spatie\MediaLibrary\MediaCollections\Models\Media as BaseMedia;

class MediaJobs extends BaseMedia
{
    protected $table = 'media_jobs';
    protected $primaryKey = 'id';
    protected $keyType = 'string';

    public $incrementing = false;

}
```

and conversions_disk is the field list on media table.

**Comment by vlados** [comment]
So from what I am seeing the problem is that the getBaseKey is called before the Media model is saved, so the id is null.
The media model is saved when the parent model is saved.
https://github.com/spatie/laravel-medialibrary/blob/c244d440250c99cbeeccfe39121e34c627564565/src/MediaCollections/FileAdder.php#L406
It never go to this line. If someone can give more light it will be helpful

**Comment by vlados** [comment]
This issue was again introduced in version 9.8.3

**Comment by freekmurze** [comment]
@vlados if you already know a solution, feel free to PR the fix + tests to make sure the bug isn't introduced again.

**Comment by salmazz** [comment]
Return value of Spatie\MediaLibrary\Support\UrlGenerator\BaseUrlGenerator::getDiskName() must be of the type string, null returned
 i have this issue again and update to the last version how can i fix it ?

**Comment by brandonserge** [comment]
Also got this issue, if I can find the fix I'll make a PR tonight.

**Comment by diazsasak** [comment]
hi @brandonserge , did you found the fix?

**Comment by SyedGhazanfar** [comment]
I have solve this by add "public" value in conversion_disk column in media table

**Comment by danFWD** [comment]
Let me add to this by saying, if you query media items directly and use an implicit `->select('etc')` in the query, you must include the 'conversion_disk' column in your select to avoid problems.

**Comment by cdwieber** [comment]
In case anyone else stumbles across this in the future, I discovered what was causing it for me. A bit of an edge case, but perhaps someone will nonetheless find it useful.

In my case it was because we had recently completed a migration from MySQL to PostgreSQL, and unfortunately not all of the primary key sequences carried over completely. Therefore, the `id` column of the `media` table was not getting properly set. I was able to fix this by running the following:

```sql
alter table media
    add constraint media_pk
        primary key (id);
create sequence media_id_seq;
alter table media alter column id set not null;
alter table media alter column id set default nextval('media_id_seq');
alter sequence media_id_seq owned by media.id;
```

If you happen to have switched to PostgreSQL recently and can find no other explanation for the error, check on this.

**Comment by Nano112** [comment]
For anyone that is facing this issue, my specific cause was my custom model to accomodate for uuid ID's.

https://github.com/spatie/laravel-medialibrary/blob/fad8e66b25d6e69af2d2cb8c5d0da12c827b1247/src/Support/PathGenerator/DefaultPathGenerator.php#L41

Was returning null as the error indicates clearly, so my solution was to add a custom getKey overide that looks like this 

```php
<?php

namespace App\Models;

use Spatie\MediaLibrary\MediaCollections\Models\Media as BaseMedia;

class Media extends BaseMedia
{

    protected $keyType = 'string';

    public $incrementing = false;


    public function getKey()
    {
        return (string) $this->uuid;
    }

}

```

**Comment by thisleenoble** [comment]
> Let me add to this by saying, if you query media items directly and use an implicit `->select('etc')` in the query, you must include the 'conversion_disk' column in your select to avoid problems.

This is an underrated comment that solved my problem. I'm using an internal table building library, and adding the disk and conversions_disk fields to the base query for the table turned out to be necessary. Thanks.
