### ISSUE TITLE
syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' MediaCollections/Models/Media.php:182

### ISSUE THREAD

**Issue by horaceho** [spatie/laravel-medialibrary#2006]
PHP 7.4.9
Laravel 7.25
Laravel Media Library 8.5

The only thing comes to mind is I am using a `s3` driver ...

```
[2020-08-20 19:24:00] local.ERROR: syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' at /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:182)
[stacktrace]
#0 /Users/ohho/Codes/Laravel/yuyeuk/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/Users/ohho/Cod...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\MediaLib...')
#2 /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php(23): spl_autoload_call('Spatie\\\\MediaLib...')
#3 [internal function]: Spatie\\MediaLibrary\\MediaLibraryServiceProvider->boot()
#4 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#5 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#7 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\\Container\\Container->call(Array)
#10 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider))
#11 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider), 27)
#12 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#13 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#14 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#15 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#16 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#17 /Users/ohho/Codes/Laravel/yuyeuk/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
```

**Comment by horaceho** [comment]
The errors may be triggered by `php artisan schedule:run` as these are the only error logs found in `laravel.log` which are generated every minute:
```
[2020-08-21 09:24:01] local.ERROR: syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' at /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:182)
[stacktrace]
#0 /Users/ohho/Codes/Laravel/yuyeuk/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/Users/ohho/Cod...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\MediaLib...')
#2 /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php(23): spl_autoload_call('Spatie\\\\MediaLib...')
#3 [internal function]: Spatie\\MediaLibrary\\MediaLibraryServiceProvider->boot()
#4 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#5 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#7 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\\Container\\Container->call(Array)
#10 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider))
#11 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider), 27)
#12 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#13 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#14 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#15 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#16 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#17 /Users/ohho/Codes/Laravel/yuyeuk/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
[2020-08-21 09:25:01] local.ERROR: syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' at /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:182)
[stacktrace]
#0 /Users/ohho/Codes/Laravel/yuyeuk/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/Users/ohho/Cod...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\MediaLib...')
#2 /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php(23): spl_autoload_call('Spatie\\\\MediaLib...')
#3 [internal function]: Spatie\\MediaLibrary\\MediaLibraryServiceProvider->boot()
#4 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#5 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#7 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\\Container\\Container->call(Array)
#10 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider))
#11 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider), 27)
#12 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#13 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#14 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#15 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#16 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#17 /Users/ohho/Codes/Laravel/yuyeuk/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
[2020-08-21 09:26:01] local.ERROR: syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' at /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:182)
[stacktrace]
#0 /Users/ohho/Codes/Laravel/yuyeuk/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/Users/ohho/Cod...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\MediaLib...')
#2 /Users/ohho/Codes/Laravel/yuyeuk/vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php(23): spl_autoload_call('Spatie\\\\MediaLib...')
#3 [internal function]: Spatie\\MediaLibrary\\MediaLibraryServiceProvider->boot()
#4 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#5 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#7 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\\Container\\Container->call(Array)
#10 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider))
#11 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Spatie\\MediaLibrary\\MediaLibraryServiceProvider), 27)
#12 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#13 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#14 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#15 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#16 /Users/ohho/Codes/Laravel/yuyeuk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#17 /Users/ohho/Codes/Laravel/yuyeuk/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
```

**Comment by horaceho** [comment]
The issue is likely `php artisan schedule:run` running the macOS older version of php. It's fixed by specify the `php` with a full path. So, instead of:
```
* * * * * cd /Users/ohho/Codes/Laravel/yuyeuk && php artisan schedule:run >> /dev/null 2>&1
```
use:
```
* * * * * cd /Users/ohho/Codes/Laravel/yuyeuk && /usr/local/bin/php artisan schedule:run >> /dev/null 2>&1
```
