### ISSUE TITLE
[BUG] Race-condition when uploading multiple media with conversions => No Query Results

### ISSUE THREAD

**Issue by ThaDaVos** [spatie/laravel-medialibrary#2213]
There seems to be an issue when uploading (I am using Ebess's package [Advanced-Nova-Media-Library](https://github.com/ebess/advanced-nova-media-library)) multiple (big) files with conversions.

All the jobs, except the last will fail with the `No Query Results` error. If one however adds `->delay(10)` at the following line: https://github.com/spatie/laravel-medialibrary/blob/21c40b4d06bd8d16c0454f553c6de4d1e35aba3e/src/Conversions/FileManipulator.php#L94
Or extends the job as follows:
```PHP
class CustomPerformConversionsJob extends PerformConversionsJob
{
    /**
     * The number of seconds before the job should be made available.
     *
     * @var \DateTimeInterface|\DateInterval|int|null
     */
    public $delay = 10;
}
```

The issue will be gone - I don't know if this issue only happens when using the Redis Driver (and Horizon) but it was a hard one to track down and find a fix for.

Like I said, I think there's a race-condition somewhere, probably firing the job off without saving the media first. It could also be that the database is slower than the queue workers resulting in a non-fixable race-condition.

What I tried: I tried delays of 1, 2 and 4 seconds but 10 seconds seems to do the most reliable job

**Comment by ThaDaVos** [comment]
Issue not fully solved...

It looks like it depends on how long the request takes - if the jobs start running before the request completes than they will fail...

**Comment by freekmurze** [comment]
I wonder where that `No Query Results` exception is being thrown. Could you provide the stack trace?

**Comment by ThaDaVos** [comment]
Here you go:
```TEXT
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [Spatie\MediaLibrary\MediaCollections\Models\Media]. in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:481
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(102): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(57): Spatie\MediaLibrary\Conversions\Jobs\PerformConversionsJob->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(122): Spatie\MediaLibrary\Conversions\Jobs\PerformConversionsJob->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#3 [internal function]: Spatie\MediaLibrary\Conversions\Jobs\PerformConversionsJob->__unserialize(Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(53): unserialize('O:58:"Spatie\\Me...')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process('redis_long', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis_long', Object(Illuminate\Queue\WorkerOptions))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis_long', 'media', Object(Illuminate\Queue\WorkerOptions))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis_long', 'media')
#11 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#18 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /var/www/html/vendor/symfony/console/Application.php(920): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
```

**Comment by ThaDaVos** [comment]
Seems to come from laravel itself -> something to do with the `SerializesModel` trait

**Comment by ThaDaVos** [comment]
I also noticed the `created_at` being before the jobs `failed_at` but the `updated_at` being way after the jobs `failed_at`

**Comment by freekmurze** [comment]
It seems to me that there error is not caused by our package.

If you find that it does, please send a PR with a fix.

**Comment by ThaDaVos** [comment]
Whoaw! Great support!... Thank you @freekmurze !

**Comment by ThaDaVos** [comment]
@freekmurze - it seems to be the same as here:
https://github.com/spatie/laravel-medialibrary/issues/1304

It's a Transaction issue... know any good solutions?
