### ISSUE TITLE
Unclear error when creating a conversion with resizing using Image::fit()

### ISSUE THREAD

**Issue by MrThursby** [spatie/laravel-medialibrary#2274]
I'm sorry if I'm mispronouncing my suggestions. I don't know much English.

Laravel 8.16.1
laravel-medialibrary 9.0.0

``` php
public function registerMediaConversions(Media $media = null):void
{
    $this->addMediaConversion('preview')
         ->fit(Manipulations::FIT_STRETCH, 150, 150);
}
```
Error when saving the model:
```
Object of class Illuminate\Http\Resources\Json\AnonymousResourceCollection could not be converted to string
```

I can't understand why the error occurs.

**Comment by MrThursby** [comment]
Log:
```
[2021-01-30 12:38:47] local.ERROR: Object of class Illuminate\Http\Resources\Json\AnonymousResourceCollection could not be converted to string {"userId":1,"exception":"[object] (Error(code: 0): Object of class Illuminate\\Http\\Resources\\Json\\AnonymousResourceCollection could not be converted to string at E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Str.php:494)
[stacktrace]
#0 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\QueryException.php(57): Illuminate\\Support\\Str::replaceArray()
#1 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\QueryException.php(40): Illuminate\\Database\\QueryException->formatMessage()
#2 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(672): Illuminate\\Database\\QueryException->__construct()
#3 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#4 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(496): Illuminate\\Database\\Connection->run()
#5 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(429): Illuminate\\Database\\Connection->affectingStatement()
#6 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2903): Illuminate\\Database\\Connection->update()
#7 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(802): Illuminate\\Database\\Query\\Builder->update()
#8 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(935): Illuminate\\Database\\Eloquent\\Builder->update()
#9 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(850): Illuminate\\Database\\Eloquent\\Model->performUpdate()
#10 E:\\Work\\bloklist\\app\\Services\\Clients\\ClientService.php(78): Illuminate\\Database\\Eloquent\\Model->save()
#11 E:\\Work\\bloklist\\app\\Http\\Controllers\\Clients\\ClientsController.php(107): App\\Services\\Clients\\ClientService->update()
#12 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\Clients\\ClientsController->update()
#13 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#14 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#15 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#16 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(692): Illuminate\\Routing\\Route->run()
#17 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#18 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#20 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#22 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#23 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#24 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#26 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(694): Illuminate\\Pipeline\\Pipeline->then()
#28 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(635): Illuminate\\Routing\\Router->runRoute()
#30 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute()
#31 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#32 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#39 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#41 E:\\Work\\bloklist\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#43 E:\\Work\\bloklist\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#45 E:\\Work\\bloklist\\app\\Http\\Middleware\\Cors.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\Cors->handle()
#47 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#49 E:\\Work\\bloklist\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 E:\\Work\\bloklist\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 E:\\Work\\bloklist\\server.php(21): require_once('E:\\\\Work\\\\bloklis...')
#52 {main}
"} 
```
