### ISSUE TITLE
Image Optimizer Is Failing When Running Parallel Test (Laravel 8.x)

### ISSUE THREAD

**Issue by firmantr3** [spatie/laravel-medialibrary#2775]
The Image Optimizer is causing error when running parallel test:

```
1) Tests\Feature\Admin\Api\Page\CrudTest::testCreateWithMainImageMedia
Expected response status code [200] but received 500.
The following exception occurred during the request:
Symfony\Component\Process\Exception\RuntimeException: Unable to launch a new process. in /builds/firmantr3/insurediy-api/vendor/symfony/process/Process.php:355
Stack trace:
#0 /builds/firmantr3/insurediy-api/vendor/symfony/process/Process.php(252): Symfony\Component\Process\Process->start(NULL, Array)
#1 /builds/firmantr3/insurediy-api/vendor/spatie/image-optimizer/src/OptimizerChain.php(101): Symfony\Component\Process\Process->run()
#2 /builds/firmantr3/insurediy-api/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Pngquant), Object(Spatie\ImageOptimizer\Image))
#3 /builds/firmantr3/insurediy-api/vendor/spatie/image/src/Image.php(178): Spatie\ImageOptimizer\OptimizerChain->optimize('/builds/firmant...')
#4 /builds/firmantr3/insurediy-api/vendor/spatie/image/src/Image.php(149): Spatie\Image\Image->performOptimization('/builds/firmant...', Array)
```

It's triggered by the responsive image generator that defined in my model:

```php
    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('main-image')
            ->singleFile()
            ->withResponsiveImages();
    }
```

I'm using version 9.x of this library on top of Laravel 8.x

**Comment by firmantr3** [comment]
turns out my env is missing GD library
