### ISSUE TITLE
FilesystemIterator::__construct(/tmp): Failed to open directory: Permission denied

### ISSUE THREAD

**Issue by ITrunsDE** [spatie/laravel-medialibrary#2886]
Hi,

this happens in my production environment. I get the following error in the laravel.log when I upload an Image that has a the following mediaConversion

**Entry.php**
```
public function registerMediaConversions(Media $media = null): void
{
    $this->addMediaConversion('thumb')
        ->fit(Manipulations::FIT_CONTAIN, 700, 750);
}
```

The following entry appears in the storage\laravel.log file:
```
[2022-04-15 07:56:38] production.ERROR: FilesystemIterator::__construct(/tmp): Failed to open directory: Permission denied {"userId":1,"exception":"[object] (UnexpectedValueException(code: 0): FilesystemIterator::__construct(/tmp): Failed to open directory: Permission denied at /www/htdocs/w123456789/test.com/vendor/spatie/image/src/GlideConversion.php:185)
```

Inside the config\media-library.php I've tried to change the following, but the error is the same.
`'temporary_directory_path' => '/www/htdocs/w123456789/test.com/storage/media-library/temp',`

These are the following packages I use from spatie.

> laravel/framework v9.8.1
> spatie/image 2.2.2
> spatie/image-optimizer 1.6.2
> spatie/laravel-medialibrary 10.3.2

When I try to upload an image without a mediaconversion, it works normally.

Thanks for Help
Sebastian

**Comment by ITrunsDE** [comment]
I've checked the upload on my dev system and i got the same error.

```
[2022-04-15 15:03:31] local.ERROR: mkdir(): Permission denied {"userId":2,"exception":"[object] (ErrorException(code: 0): mkdir(): Permission denied at /home/pi/project/test/vendor/spatie/temporary-directory/src/TemporaryDirectory.php:82)
[stacktrace]
#0 /home/pi/project/test/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/pi/project/test/vendor/spatie/temporary-directory/src/TemporaryDirectory.php(82): mkdir()
#3 /home/pi/project/test/vendor/spatie/laravel-medialibrary/src/Conversions/FileManipulator.php(57): Spatie\\TemporaryDirectory\\TemporaryDirectory->path()
#4 /home/pi/project/test/vendor/spatie/laravel-medialibrary/src/Conversions/Jobs/PerformConversionsJob.php(27): Spatie\\MediaLibrary\\Conversions\\FileManipulator->performConversions()
#
```

**Comment by timothyasp** [comment]
Seems like this might be related to #2891
