### ISSUE TITLE
Grammar::parameterize(): Argument #1 ($values) must be of type array, int given

### ISSUE THREAD

**Issue by theupriser** [spatie/laravel-medialibrary#3359]
Hello,

I've found a bug. I stumbled upon this after updating to the latest version of laravel and media-library.
Is this something that can be easily fixed?

With kind regards,

Rick

``Could not finish importing car photo's {"carId":1037535,"images":{"1":"/var/www/vhosts/../.../../car-1.jpg"},"exception":"[object] (TypeError(code: 0): Illuminate\\Database\\Grammar::parameterize(): Argument #1 ($values) must be of type array, int given, called in /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 1040 at /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:175)
[stacktrace]
#0 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(1040): Illuminate\\Database\\Grammar->parameterize()
#1 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}()
#2 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#3 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map()
#4 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(1041): Illuminate\\Support\\Collection->map()
#5 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php(202): Illuminate\\Database\\Query\\Grammars\\Grammar->compileInsert()
#6 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(1070): Illuminate\\Database\\Query\\Grammars\\MySqlGrammar->compileInsert()
#7 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3383): Illuminate\\Database\\Query\\Grammars\\Grammar->compileInsertGetId()
#8 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(186): Illuminate\\Database\\Query\\Builder->insertGetId()
#9 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(96): Illuminate\\Queue\\DatabaseQueue->pushToDatabase()
#10 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(315): Illuminate\\Queue\\DatabaseQueue->Illuminate\\Queue\\{closure}()
#11 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(97): Illuminate\\Queue\\Queue->enqueueUsing()
#12 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\DatabaseQueue->push()
#13 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(246): Illuminate\\Queue\\Queue->pushOn()
#14 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#15 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#16 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch()
#17 /var/www/vhosts/../../laravelinstallation/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(388): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#18 /var/www/vhosts/../../laravelinstallation/vendor/spatie/laravel-medialibrary/src/Conversions/FileManipulator.php(98): dispatch()
#19 /var/www/vhosts/../../laravelinstallation/vendor/spatie/laravel-medialibrary/src/Conversions/FileManipulator.php(40): Spatie\\MediaLibrary\\Conversions\\FileManipulator->dispatchQueuedConversions()
#20 /var/www/vhosts/../../laravelinstallation/vendor/spatie/laravel-medialibrary/src/MediaCollections/Filesystem.php(37): Spatie\\MediaLibrary\\Conversions\\FileManipulator->createDerivedFiles()
#21 /var/www/vhosts/../../laravelinstallation/vendor/spatie/laravel-medialibrary/src/MediaCollections/FileAdder.php(432): Spatie\\MediaLibrary\\MediaCollections\\Filesystem->add()
#22 /var/www/vhosts/../../laravelinstallation/vendor/spatie/laravel-medialibrary/src/MediaCollections/FileAdder.php(414): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->processMediaItem()
#23 /var/www/vhosts/../../laravelinstallation/vendor/spatie/laravel-medialibrary/src/MediaCollections/FileAdder.php(333): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->attachMedia()
#24 /var/www/vhosts/../../laravelinstallation/app/Jobs/ProcessCarPhotos.php(65): Spatie\\MediaLibrary\\MediaCollections\\FileAdder->toMediaCollection()`

**Comment by theupriser** [comment]
This also fails when I try to regenerate

**Comment by theupriser** [comment]
I believe i've made a mistake of my own. I've got it fixed.
